### ISSUE TITLE
GMRES-E fixes

### ISSUE THREAD

**Issue by jhabriel** [nidtec-una/krysbas-dev#69]
### TODO:

- [ ] Output `kdvec` in all solvers. @jhabriel 
- [ ] Use `l` in LGMRES and `d` in GMRES-E. @jhabriel 
- [ ] Issue #68 @jccf19 
- [ ] Encapsulation of harmonic Ritz vectors method. @gusespinola
